### ISSUE TITLE
doesnt compile.

### ISSUE THREAD

**Issue by NicTanghe** [leptos-rs/leptos-website#22]
error[E0282]: type annotations needed for `Box<_>`
  --> /home/tanghe/.cargo/registry/src/index.crates.io-6f17d22bba15001f/time-0.3.25/src/format_description/parse/mod.rs:83:9
   |
83 |     let items = format_items
   |         ^^^^^
...
86 |     Ok(items.into())
   |              ---- type must be known at this point

**Comment by NicTanghe** [comment]
ok then

**Comment by NicTanghe** [comment]
I`ll try these next https://github.com/leptos-rs/leptos-website/issues/17

**Comment by gbj** [comment]
The website does compile; I just deployed it yesterday so closed this issue as stale. 

The error you're seeing is due to a newer Rust tool chain with an older version of `time`. `cargo update` may well be the fix, if you're trying to run it locally and having issues. Other useful things include making sure you're on the latest `cargo-leptos`, `cargo update`, `cargo clean`, updating Rust tool chain, etc. 

If this is for your own project and you're having issues, feel free to open an issue with a reproduction in the main repo. Ultimately though this repo is for the leptos.dev website, so if you're having issues compiling it that the actual deployed site is having it's a relatively lower priority for me to write out a reply.
